#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

docs_folder_count=$(git diff --cached --name-only | grep "docs" | wc -l)
current_branch=$(git branch --show-current)

if [ 0 -lt $docs_folder_count ] && [ "prod" != "$current_branch" ]; then
	echo "docs/ is commited not on the 'prod' branch. Commit rejected."
	exit 1
fi